import assert from "node:assert/strict";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import * as z from "zod/v4";
import { TOOL_DEFINITIONS } from "../src/tool-registry.mjs";
import { FlowstackTools } from "../src/tools.mjs";
import { SERVER_PACKAGE, SERVER_VERSION } from "../src/constants.mjs";

const root = resolve(import.meta.dirname, "..");
const generated = join(root, "generated");
const docs = join(root, "docs");
const check = process.argv.includes("--check");
const packageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8"));

assert.equal(packageJson.name, "@flowstack-ui/mcp");
assert.equal(packageJson.name, SERVER_PACKAGE);
assert.equal(packageJson.version, SERVER_VERSION);
assert.match(packageJson.version, /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/u, "MCP package version must be exact");
assert.equal(packageJson.private, undefined, "MCP package must be publishable");
assert.deepEqual(packageJson.publishConfig, { access: "public", registry: "https://registry.npmjs.org/" });
assert.deepEqual(packageJson.repository, { type: "git", url: "git+https://github.com/flowstack-ui/agent-tools.git", directory: "packages/mcp" });

assert.equal(new Set(TOOL_DEFINITIONS.map(({ name }) => name)).size, TOOL_DEFINITIONS.length, "tool names must be unique");
assert.equal(new Set(TOOL_DEFINITIONS.map(({ method }) => method)).size, TOOL_DEFINITIONS.length, "tool methods must be unique");
for (const { name, method } of TOOL_DEFINITIONS) assert.equal(typeof FlowstackTools.prototype[method], "function", `${name} points to non-callable method ${method}`);

const tools = TOOL_DEFINITIONS.map(({ name, method, description, inputSchema }) => ({
  name,
  method,
  description,
  inputSchema: z.toJSONSchema(inputSchema, { target: "draft-7", reused: "inline" })
}));

const registry = { schema: "flowstack.mcp-tool-registry.v1", package: SERVER_PACKAGE, version: SERVER_VERSION, transport: "stdio", tools };
const capabilities = {
  schema: "flowstack.mcp-capabilities.v1",
  package: SERVER_PACKAGE,
  version: SERVER_VERSION,
  transport: { kind: "stdio", modern: "2026-07-28", legacy: "serve" },
  resolution: { policies: ["auto", "installed", "locked"], versionPolicy: "exact-only", network: false },
  toolNames: tools.map(({ name }) => name),
  toolCount: tools.length
};
const markdown = `# FLOWSTACK MCP tools\n\nGenerated from \`src/tool-registry.mjs\`. Do not edit this file directly.\n\n${tools.map((tool) => `## ${tool.name}\n\n${tool.description}\n\nInput schema:\n\n\`\`\`json\n${JSON.stringify(tool.inputSchema, null, 2)}\n\`\`\``).join("\n\n")}\n`;
const outputs = new Map([
  [join(generated, "tool-registry.json"), `${JSON.stringify(registry, null, 2)}\n`],
  [join(generated, "capabilities.json"), `${JSON.stringify(capabilities, null, 2)}\n`],
  [join(docs, "tools.md"), markdown]
]);

await mkdir(generated, { recursive: true });
await mkdir(docs, { recursive: true });
if (check) {
  for (const [path, expected] of outputs) assert.equal(await readFile(path, "utf8"), expected, `${path} is stale`);
  assert.deepEqual((await readdir(generated)).sort(), ["capabilities.json", "tool-registry.json"]);
  console.log(`Verified ${tools.length} generated MCP tools and capability inventory.`);
} else {
  for (const [path, content] of outputs) await writeFile(path, content);
  console.log(`Generated ${tools.length} MCP tools and capability inventory.`);
}
